# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведення уроку з вибраного предмету')),
                ('notes', models.TextField(blank=True, verbose_name='Додаткові нотатки')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Назва групи для якої проводиться заняття')),
                ('present_students', models.ManyToManyField(blank=True, db_table='students_lecture_present_students', to='students.Student', verbose_name='Відвідувачі заняття')),
            ],
            options={
                'verbose_name': 'Перелік занять',
                'verbose_name_plural': 'Перелік занять',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва навчального року')),
                ('start_year_date', models.DateField(verbose_name='Дата початку навчального року')),
                ('end_year_date', models.DateField(verbose_name='Дата завершення навчального року')),
                ('notes', models.TextField(blank=True, verbose_name='Додаткові нотатки')),
            ],
            options={
                'verbose_name': 'Навчальний рік',
                'verbose_name_plural': 'Навчальні роки',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Назва предмету')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата проведення екзамену')),
                ('notes', models.TextField(blank=True, verbose_name='Додаткові нотатки')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Subject', verbose_name='Назва предмету(лекції)'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.SchoolYear', verbose_name='Назва навчального року'),
        ),
        migrations.AddField(
            model_name='student',
            name='lectures',
            field=models.ManyToManyField(db_table='students_lecture_present_students', to='students.Lecture', verbose_name='Відвідувані заннятя'),
        ),
    ]
