# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20160817_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата та час проведеня екзамену')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='Група для якої проводитиметься екзамен')),
            ],
            options={
                'verbose_name_plural': 'Екзамени',
                'verbose_name': 'Екзамен',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=256, verbose_name='Прізвище')),
                ('middle_name', models.CharField(blank=True, default='', max_length=256, verbose_name='По-батькові')),
                ('salary', models.IntegerField(verbose_name='Середня зарабітня платня за останній рік')),
            ],
            options={
                'verbose_name_plural': 'Викладачі',
                'verbose_name': 'Викладач',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='teaсher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Teacher', verbose_name='Викладач'),
        ),
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Subject', verbose_name='Предмет з якого проводитиметься екзамен'),
        ),
    ]
